# Generated by Django 5.1.4 on 2024-12-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_client_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhar',
            field=models.CharField(default='NA', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.BigIntegerField(default=1000100010, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='aadhar',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientName',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pan',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
