# Generated by Django 5.1.4 on 2024-12-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee_aadhar_employee_mobile_alter_client_aadhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhar',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
