# Generated by Django 5.1.4 on 2024-12-21 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_employee_aadhar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='aadhar',
        ),
    ]
