# Generated by Django 5.1.4 on 2024-12-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_employee_aadhar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='aadhar',
            new_name='e_aadhar',
        ),
    ]
