# Generated by Django 5.1.4 on 2024-12-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_employee_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='emp_name',
        ),
    ]
