# Generated by Django 5.1.4 on 2024-12-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_name_employee_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_aadhar',
            field=models.CharField(blank=True, default='NA', max_length=15, null=True),
        ),
    ]
