# Generated by Django 5.1.4 on 2024-12-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='Ahmedabad', max_length=30),
        ),
    ]
