# Generated by Django 5.1.4 on 2024-12-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_client_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='aadhar',
            new_name='sec_mobile',
        ),
        migrations.RemoveField(
            model_name='client',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pan',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
