# Generated by Django 5.1.4 on 2024-12-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_employee_emp_aadhar_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='referredBy',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
