# Generated by Django 5.1.4 on 2024-12-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_client_referredby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sec_mobile',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
