# Generated by Django 5.1.4 on 2024-12-24 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_client_sec_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='billing_month',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='status',
            field=models.CharField(choices=[('Half Documents Submitted', 'Half Documents Submitted'), ('Full Documents Submitted', 'Full Documents Submitted'), ('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Filed', 'Filed')], default='Not Started', max_length=60),
        ),
        migrations.AddField(
            model_name='service',
            name='billing_cycle',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly'), ('Annually', 'Annually')], default='Monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='sec_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
