# Generated by Django 5.1.4 on 2024-12-25 06:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_clientservice_billing_month_clientservice_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_date', models.DateField(default=datetime.date.today)),
                ('clientService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientservice')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
