# Generated by Django 5.1.4 on 2024-12-25 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_billing_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientservice',
            name='billing_month',
        ),
        migrations.RemoveField(
            model_name='service',
            name='billing_cycle',
        ),
        migrations.AddField(
            model_name='clientservice',
            name='billing_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='status',
            field=models.CharField(choices=[('Half Documents Submitted', 'Half Documents Submitted'), ('Full Documents Submitted', 'Full Documents Submitted'), ('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Filed', 'Filed')], default='Not Started', max_length=100),
        ),
    ]
