# Generated by Django 5.1.4 on 2024-12-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_clientservice_billing_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
