# Generated by Django 5.1.4 on 2024-12-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_clientservice_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='status',
            field=models.CharField(choices=[('Partial Documents Submitted', 'Partial Documents Submitted'), ('Full Documents Submitted', 'Full Documents Submitted'), ('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Filed', 'Filed')], default='Not Started', max_length=100),
        ),
    ]
