# Generated by Django 5.1.4 on 2024-12-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_clientservice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='fee_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Discounted', 'Discounted'), ('Partial', 'Partial')], max_length=50, null=True),
        ),
    ]
