# Generated by Django 5.1.4 on 2024-12-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_billing_fee_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='fees',
            new_name='fees_recieved',
        ),
    ]
