# Generated by Django 5.1 on 2025-01-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_billing_outstanding_amt_billing_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff')], default='Staff', max_length=25),
        ),
    ]
